In [1]:
from transformers import AutoTokenizer
from transformers import XLNetTokenizer, TFXLNetLMHeadModel

In [3]:
tokenizer=AutoTokenizer.from_pretrained('hfl/chinese-xlnet-base')
model = TFXLNetLMHeadModel.from_pretrained("hfl/chinese-xlnet-base")

2022-01-24 15:07:15.700304: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-24 15:07:20.986376: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10421 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1
2022-01-24 15:07:20.988388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 10421 MB memory:  -> device: 1, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1
2022-01-24 15:07:20.989995: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/t

In [11]:
import tensorflow as tf
import numpy as np
input_ids = tf.constant(tokenizer.encode("Hello, my dog is very <mask>", add_special_tokens=True))[
    None, :
]  # We will predict the masked token

perm_mask = np.zeros((1, input_ids.shape[1], input_ids.shape[1]))
perm_mask[:, :, -1] = 1.0  # Previous tokens don't see last token

target_mapping = np.zeros(
    (1, 1, input_ids.shape[1])
)  # Shape [1, 1, seq_length] => let's predict one token
target_mapping[
    0, 0, -1
] = 1.0  # Our first (and only) prediction will be the last token of the sequence (the masked token)

outputs = model(
    input_ids,
    perm_mask=tf.constant(perm_mask, dtype=tf.float32),
    target_mapping=tf.constant(target_mapping, dtype=tf.float32),
)
next_token_logits = outputs[0]
next_token_logits

<tf.Tensor: shape=(1, 1, 32000), dtype=float32, numpy=
array([[[ 4.9395194 , -0.5041997 , -0.48420405, ..., -0.46310532,
         -0.08855915,  0.16015184]]], dtype=float32)>

In [5]:
outputs

TFXLNetLMHeadModelOutput(loss=None, logits=<tf.Tensor: shape=(1, 1, 32000), dtype=float32, numpy=
array([[[ 4.9395194 , -0.5041997 , -0.48420405, ..., -0.46310532,
         -0.08855915,  0.16015184]]], dtype=float32)>, mems=(<tf.Tensor: shape=(17, 1, 768), dtype=float32, numpy=
array([[[-0.00773535,  0.00266788, -0.00799373, ...,  0.02040497,
         -0.01341878,  0.02465967]],

       [[ 0.01795992, -0.01822837, -0.01776422, ...,  0.04881001,
          0.02405427, -0.00601735]],

       [[ 0.03020168,  0.02440496,  0.00828683, ...,  0.02402874,
          0.01149149, -0.00781375]],

       ...,

       [[ 0.02233568, -0.00095854, -0.00444888, ...,  0.0084238 ,
         -0.0224812 , -0.0018688 ]],

       [[ 0.01402227, -0.05273601, -0.01965438, ...,  0.00811852,
         -0.0376983 ,  0.00836642]],

       [[-0.08334228, -0.06672204, -0.06840936, ...,  0.02247671,
         -0.04441682,  0.01747068]]], dtype=float32)>, <tf.Tensor: shape=(17, 1, 768), dtype=float32, numpy=
array([[[ 0.0

In [8]:
from dataclasses import dataclass
from typing import List
@dataclass
class Input:
    input_ids:List
    token_type_ids:List
    attention_mask: List
    def concat(self,input_ids:List,token_type_ids:List,attention_mask: List):
        self.input_ids.extend(input_ids)
        self.token_type_ids.extend(token_type_ids)
        self.attention_mask.extend(attention_mask)
a=Input([1,2,3],[1],[2])

In [11]:
t.decode([4925,30])
t.decode([12967,18])

'客户。'

In [12]:
t("客撒洞察生发出asgfi户。",add_special_tokens=False,max_length=10,padding='max_length')

{'input_ids': [19, 907, 2942, 1476, 2650, 153, 5967, 2798, 1232, 14176, 1924, 18], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [7]:
import json
with open('vocab.json','w') as f:
    json.dump(t.vocab, f)

In [3]:
import spacy
import json
with open('vocab.json', 'r') as f:
    a=json.load(f)

In [ ]:
from spacy.tokens import Doc
Doc()